import { BrowserWindow,app } from "electron";
import { createAppMenu } from "./utils/createAppMenu";
import path from "path";

const isDev = !app.isPackaged;

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

const iconPath = isDev
    ? path.join(app.getAppPath(), "assets", "topBar.png")
    : path.join(process.resourcesPath, "assets", "topBar.png");

export const createWindow = (): BrowserWindow => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 400,
    resizable: false,
    darkTheme: false,
    icon: iconPath, // ✅ window icon (for top bar)
    autoHideMenuBar: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
    
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
    // mainWindow.webContents.openDevTools();

   // Create the menu here
  createAppMenu(mainWindow);
    return mainWindow;
};